# Generated by Django 5.2.1 on 2025-05-16 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, unique=True)),
                ('internal_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, unique=True)),
                ('internal_name', models.CharField(max_length=255, unique=True)),
                ('temperature', models.FloatField(default=0.5)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llms', to='lyrical.llmprovider')),
                ('comments', models.TextField(default="")),
                ('cost', models.FloatField(default=0.0)),
                ('features', models.JSONField(default=dict)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, unique=False, default='')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrical.llmprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='default_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lyrical.llm'),
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspaces", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("theme", models.TextField(default="")),
                ("lyrics", models.TextField(default="")),
                ("llm_temperature", models.FloatField(default=0.5)),
                ("llm", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="lyrical.llm")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="songs", to="lyrical.workspace")),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("system", "System"), ("user", "User"), ("assistant", "Assistant")], max_length=50)),
                ("content", models.TextField()), 
                ("llm", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="lyrical.llm")),
                ("song", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="lyrical.song")),
            ],
        ),      
    ]
