# Generated by Django 5.2.1 on 2025-05-22 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lyrical", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMProvider",
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, unique=True)),
                ('internal_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="LLM",
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, unique=True)),
                ('internal_name', models.CharField(max_length=255, unique=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="llms", to="lyrical.llmprovider")),
                ('cost_per_1m_tokens', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(model_name="user", name="llm_max_tokens", field=models.IntegerField(default=2000)),
        migrations.AddField(model_name="user", name="llm_temperature", field=models.FloatField(default=0.2)),
        migrations.AddField(model_name="user", name="llm_model", field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.PROTECT, to="lyrical.llm")),
        migrations.AddField(model_name='user', name='llm_model_summarise', field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.PROTECT, related_name='users_summarise', to='lyrical.llm')),
        migrations.AddField(model_name="user", name="song_name_ends_with", field=models.CharField(default="", max_length=255)),
        migrations.AddField(model_name="user", name="song_name_gen_count", field=models.IntegerField(default=5)),
        migrations.AddField(model_name="user", name="song_name_length_max", field=models.IntegerField(default=5)),
        migrations.AddField(model_name="user", name="song_name_length_min", field=models.IntegerField(default=1)),
        migrations.AddField(model_name="user", name="song_name_starts_with", field=models.CharField(default="", max_length=255)),
        migrations.AddField(model_name="user", name="song_name_theme_exc", field=models.CharField(default="", max_length=255)),
        migrations.AddField(model_name="user", name="song_name_theme_inc", field=models.CharField(default="", max_length=255)),
        migrations.AddField(model_name="user", name="song_name_words_exc", field=models.CharField(default="", max_length=255)),
        migrations.AddField(model_name="user", name="song_name_words_inc", field=models.CharField(default="", max_length=255)),        
        migrations.CreateModel(
            name="Song",
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('theme', models.TextField(default="")),
                ('narrative', models.TextField(default="")),
                ('mood', models.TextField(default="")),
                ('structure', models.TextField(default="")),
                ('structure_custom_request', models.TextField(default='')),
                ('structure_vocalisation_level', models.IntegerField(default=2, choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('structure_vocalisation_terms', models.CharField(default='ah, ahh, oh, ooh, whoa', max_length=255)),
                ('structure_average_syllables', models.IntegerField(default=8)),
                ('structure_verse_lines', models.IntegerField(default=4)),
                ('structure_pre_chorus_lines', models.IntegerField(default=4)),
                ('structure_chorus_lines', models.IntegerField(default=4)),
                ('structure_bridge_lines', models.IntegerField(default=4)),
                ('structure_intro_lines', models.IntegerField(default=4)),
                ('structure_outro_lines', models.IntegerField(default=4)),
                ('structure_vocalisation_lines', models.IntegerField(default=2)),
                ('stage', models.CharField(choices=[("new", "New"), ("liked", "Liked"), ("disliked", "Disliked"), ("generated", "Generated"), ("published", "Published")], default="new", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="songs", to=settings.AUTH_USER_MODEL)),
                ('needs_summarisation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SongStructureTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("custom_request", models.TextField(default="")),
                ("vocalisation_level", models.IntegerField(choices=[(0, "None"), (1, "Low"), (2, "Medium"), (3, "High")], default=2,)),
                ("vocalisation_terms", models.CharField(default="ah, ahh, oh, ooh, whoa", max_length=255)),
                ("average_syllables", models.IntegerField(default=8)),
                ("verse_lines", models.IntegerField(default=4)),
                ("pre_chorus_lines", models.IntegerField(default=4)),
                ("chorus_lines", models.IntegerField(default=4)),
                ("bridge_lines", models.IntegerField(default=4)),
                ("intro_lines", models.IntegerField(default=4)),
                ("outro_lines", models.IntegerField(default=4)),
                ("vocalisation_lines", models.IntegerField(default=2)),
                ("structure", models.TextField(default="")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="structure_templates", to=settings.AUTH_USER_MODEL,)),
            ],
        ),
        migrations.CreateModel(
            name="SongMetadata",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=255)),
                ("value", models.TextField(default="")),
                ("song", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="metadata", to="lyrical.song")),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[("theme", "Theme"), ("narrative", "Narrative"), ("mood", "Mood"), ('instrumental-intro', 'Instrumental Intro'), ("intro", "Intro"), ("verse", "Verse"), 
                                                   ("chorus", "Chorus"), ("bridge", "Bridge"), ("pre-chorus", "Pre-Chorus"), ("outro", "Outro"), ("vocalisation", "Vocalisation")], max_length=50)),
                ('text', models.TextField(default="")),
                ('hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="lyrical.song")),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('style', 'style'), ('lyrics', 'Lyrics'), ('rhyme', 'Rhyme'), ('summary', 'Summary')], max_length=50)),
                ('role', models.CharField(choices=[("system", "System"), ("user", "User"), ("assistant", "Assistant")], max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="lyrical.song")),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lyrics",
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[("intro", "Intro"), ("verse", "Verse"), ("chorus", "Chorus"), ("bridge", "Bridge"), ("pre-chorus", "Pre-Chorus"), 
                                                   ("outro", "Outro"), ("vocalisation", "Vocalisation")], max_length=50)),
                ('index', models.IntegerField(default=0)),
                ('words', models.TextField(default="")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lyrics", to="lyrical.song")),
            ],
        ),
        migrations.CreateModel(
            name="UserAPIKey",
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(default="", max_length=255)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lyrical.llmprovider")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="api_keys", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
