# Generated by Django 5.2 on 2025-04-15 00:03

from django.db import migrations


def add_data(apps, schema_editor):
    llm_provider = apps.get_model("lyrical", "LLMProvider")
    llm = apps.get_model("lyrical", "LLM")

    llm_provider.objects.create(display_name="OpenAI", internal_name="openai")
    llm_provider.objects.create(display_name="Anthropic", internal_name="anthropic")
    llm_provider.objects.create(display_name="Google", internal_name="gemini")
    llm_provider.objects.create(display_name="Ollama", internal_name="ollama")

    # for model in litellm.utils.get_valid_models():
    #     print(model)

    llm.objects.create(display_name="GPT:4.1", internal_name="gpt-4.1", provider=llm_provider.objects.get(internal_name="openai"), cost_per_1m_tokens=16.0)
    llm.objects.create(display_name="Claude:3.5", internal_name="claude-3-5-sonnet-latest", provider=llm_provider.objects.get(internal_name="anthropic"), cost_per_1m_tokens=5.0)
    llm.objects.create(display_name="Claude:3.7", internal_name="claude-3-7-sonnet-latest", provider=llm_provider.objects.get(internal_name="anthropic"), cost_per_1m_tokens=15.0)
    llm.objects.create(display_name="Gemini-Flash:2.0", internal_name="gemini-2.0-flash", provider=llm_provider.objects.get(internal_name="gemini"), cost_per_1m_tokens=1.20)
    llm.objects.create(display_name="Gemini-Flash:1.5", internal_name="gemini-1.5-flash", provider=llm_provider.objects.get(internal_name="gemini"), cost_per_1m_tokens=0.10)
    llm.objects.create(display_name="Gemma3:4b", internal_name="gemma3:4b", provider=llm_provider.objects.get(internal_name="ollama"), cost_per_1m_tokens=0.0)


def remove_data(apps, schema_editor):
    apps.get_model("lyrical", "LLM").objects.all().delete()
    apps.get_model("lyrical", "LLMProvider").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("lyrical", "0002_schema"),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
