# Generated by Django 5.2 on 2025-04-15 00:03

from django.db import migrations
from django.contrib.auth.hashers import make_password


def add_data(apps, schema_editor):
    users = apps.get_model('lyrical', 'User')

    users.objects.create(username='admin', password=make_password('admin'), email='admin@example.com', first_name='Admin', last_name='Admin', is_superuser=True, is_staff=True)
    users.objects.create(username='mpetrou', password=make_password('mike'), email='mike@example.com', first_name='Mike', last_name='Jones', is_superuser=True, is_staff=True)

def remove_data(apps, schema_editor):
    users = apps.get_model('lyrical', 'User')
    users.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("lyrical", "0002_schema"),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
