# Generated by Django 5.2 on 2025-04-15 00:03

from django.db import migrations
import os

def add_data(apps, schema_editor):
    llm_provider = apps.get_model("lyrical", "LLMProvider")
    llm = apps.get_model("lyrical", "LLM")
    user = apps.get_model("lyrical", "User")
    user_api_key = apps.get_model("lyrical", "UserAPIKey")

    llm_provider.objects.create(name="OpenAI")
    llm_provider.objects.create(name="Anthropic")
    llm_provider.objects.create(name="Google")
    llm_provider.objects.create(name="Ollama")

    llm.objects.create(name="GPT 4.1", model_name="gpt-4.1", provider=llm_provider.objects.get(name="OpenAI"))
    llm.objects.create(name="GPT 4o", model_name="gpt-4o", provider=llm_provider.objects.get(name="OpenAI"))
    llm.objects.create(name="GPT 4o mini", model_name="gpt-4o-mini", provider=llm_provider.objects.get(name="OpenAI"))
    llm.objects.create(name="Claude 3.5", model_name="claude-3-5-haiku-latest", provider=llm_provider.objects.get(name="Anthropic"))
    llm.objects.create(name="Claude 3.7", model_name="claude-3-7-sonnet-latest", provider=llm_provider.objects.get(name="Anthropic"))
    llm.objects.create(name="Gemini 2.0", model_name="gemini-2.0-flash", provider=llm_provider.objects.get(name="Google"))
    llm.objects.create(name="Gemini 2.5", model_name="gemini-2.5-flash", provider=llm_provider.objects.get(name="Google"))
    llm.objects.create(name="Gemma3 12b", model_name="gemma3-12b", provider=llm_provider.objects.get(name="Ollama"))
    llm.objects.create(name="Gemma3 4b", model_name="gemma3-4b", provider=llm_provider.objects.get(name="Ollama"))

    open_ai_api_key = os.getenv("OPENAI_API_KEY")
    anthropic_api_key = os.getenv("ANTHROPIC_API_KEY")
    google_api_key = os.getenv("GOOGLE_API_KEY")

    user_api_key.objects.create(user=user.objects.get(username="mpetrou"), provider=llm_provider.objects.get(name="OpenAI"),api_key=open_ai_api_key)
    user_api_key.objects.create(user=user.objects.get(username="mpetrou"), provider=llm_provider.objects.get(name="Anthropic"), api_key=anthropic_api_key)
    user_api_key.objects.create(user=user.objects.get(username="mpetrou"), provider=llm_provider.objects.get(name="Google"), api_key=google_api_key)


def remove_data(apps, schema_editor):
    apps.get_model("lyrical", "UserAPIKey").objects.all().delete()
    apps.get_model("lyrical", "User").objects.all().delete()
    apps.get_model("lyrical", "LLM").objects.all().delete()
    apps.get_model("lyrical", "LLMProvider").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("lyrical", "0003_add_users"),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
