# Generated by Django 5.2 on 2025-04-15 00:03

from django.db import migrations
from pathlib import Path
from ..services.utils.prompts import get_system_prompt, get_user_prompt
import os


def add_data(apps, schema_editor):
    users = apps.get_model("lyrical", "User")
    songs = apps.get_model("lyrical", "Song")

    user = users.objects.get(username="mpetrou")

    songs.objects.create(user=user, name="Chasing Dreams", stage="new")
    songs.objects.create(user=user, name="The End Of Me", stage="new")
    songs.objects.create(user=user, name="Dance With Me Tonight", stage="new")

    songs.objects.create(user=user, name="From The Ashes", stage="liked")
    songs.objects.create(user=user, name="Dancing On My Own", stage="liked")
    songs.objects.create(user=user, name="How To Shine", stage="liked")
    songs.objects.create(user=user, name="Find Your Fire", stage="liked")

    songs.objects.create(user=user, name="Move Myself", stage="disliked")
    songs.objects.create(user=user, name="Dream Of Me", stage="disliked")
    songs.objects.create(user=user, name="Sound Of Summer", stage="disliked")
    songs.objects.create(user=user, name="Dont Hold Back", stage="disliked")


    


def remove_data(apps, schema_editor):
    users = apps.get_model("lyrical", "User")
    songs = apps.get_model("lyrical", "Song")

    songs.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("lyrical", "0004_add_users"),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
