# Generated by Django 5.2 on 2025-04-15 00:03

from django.db import migrations
from pathlib import Path
from ..services.utils.prompts import get_system_prompt, get_user_prompt
from .. import models


published_songs = [
    'Dance With Me Tonight', 'Dancing In The Daylight', 'Dancing On My Own', 'Electric Tonight', 'How To Shine', 'Lighting It Up', 'Move Myself', 'Moving To My Own Song', 
    'Seashells In The Sand', 'Sunset Echoes', 'This Moment', 'A New Dawn', 'After the Rain', 'Autumn Leaves', 'Beautiful Life', 'Believe in Magic', 'Born For This', 'Bright Future', 
    'Carefree Summer Nights', 'Chasing Dreams', 'Dance All Night', 'Dancing In The Twilight', 'Dont Hold Back', 'Dream Of Me', 'Endless Summer', 'Eternal Waves', 'Feel The Heat', 
    'Finally Free', 'Find Your Fire', 'Find Your Way', 'From The Ashes', 'Heart of Chaos', 'Hidden In The Night', 'I Am Strong', 'I Can Fly', 'I Create', 'In My Dreams', 'In My Mind', 
    'In My Sea', 'In The Rain', 'Into the Night', 'Invincible', 'Leave A Trace', 'Light Your Fire', 'Light Your Way', 'Morning Glow', 'Ocean of Dreams', 'Run Free', 'Shine Like Stars', 
    'Shine Your Light', 'Silent Echoes', 'Smile Through The Rain', 'Sound Of Summer', 'Stronger Every Day', 'Summer In Your Soul', 'Summer Nights', 'Summertime', 'Sunrise', 'The End Of Me', 
    'Unbreakable', 'Under The Sun', 'Unseen Love', 'Unstoppable', 'Wild and Free', 'Winner'
    ]


liked_songs = [
    'Before The Storm', 'Chase The Sun', 'Climb Higher', 'Dare To Dream', 'Garden Of Dreams', 'Into The Wild', 'Light The Sky',
    'Own The Moment', 'Stand Tall', 'Summer Dreams', 'Hold On Tight', 'One More Step', 'Heart On Fire',
    'Own The Fight', 'New Sunrise', 'Forgotten Dreams', 'Every Heartbeat', 'We Are One', 'Hidden Sights',
    'Stand As One', 'Before The Thunder', 'Sun Will Shine', 'Dreams Will Come', 'Still We Rise', 
    'Reason To Smile', 'Never Give Up'
    ]


def add_data(apps, schema_editor):
    user = models.User.objects.get(username="mpetrou")

    # create all of the published songs for the user
    for song_name in published_songs:
        song = models.Song(user=user, name=song_name, stage="published")
        song.apply_user_defaults(user)
        song.save()

    # create all of the liked songs for the user
    for song_name in liked_songs:
        song = models.Song(user=user, name=song_name, stage="liked")
        song.apply_user_defaults(user)
        song.save()

    
def remove_data(apps, schema_editor):
    users = apps.get_model("lyrical", "User")
    songs = apps.get_model("lyrical", "Song")

    songs.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("lyrical", "0004_add_users"),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
