# Generated by Django 5.2.1 on 2025-05-16 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrical', '0004_add_llms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lyrical.llm'),
        ),
    ]
