# Generated by Django 5.2 on 2025-04-15 00:03

from django.db import migrations
from pathlib import Path
from ..services.utils.prompts import get_system_prompt, get_user_prompt
import os


def add_data(apps, schema_editor):
    users = apps.get_model("lyrical", "User")
    songs = apps.get_model("lyrical", "Song")

    user = users.objects.get(username="mpetrou")


    


def remove_data(apps, schema_editor):
    users = apps.get_model("lyrical", "User")
    songs = apps.get_model("lyrical", "Song")

    users.objects.all().delete()
    songs.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("lyrical", "0004_add_llms"),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
