# Generated by Django 5.2.1 on 2025-05-29 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lyrical", "0005_add_songs"),
    ]

    operations = [
    ]
