# Generated by Django 5.2 on 2025-04-15 00:03

from django.db import migrations
from django.contrib.auth.hashers import make_password


def add_data(apps, schema_editor):
    """
    Adds users to the database.
    """
    users = apps.get_model('quizly', 'User')
    users.objects.create(username='admin', password=make_password('admin'), email='admin@example.com', first_name='Admin', last_name='Admin', is_superuser=True, is_staff=True)
    users.objects.create(username='mike74', password=make_password('mike'), email='mike@example.com', first_name='Mike', last_name='Jones', is_superuser=True, is_staff=True)
    users.objects.create(username='bobbyc_88', password=make_password('bob'), email='bob@example.com', first_name='Bob', last_name='Carter', is_superuser=False)
    users.objects.create(username='emma.w', password=make_password('emma'), email='emma@example.com', first_name='Emma', last_name='Wilson', is_superuser=False)
    users.objects.create(username='james_theguy', password=make_password('james'), email='james@example.com', first_name='James', last_name='Harris', is_superuser=False)
    users.objects.create(username='sally_mitch', password=make_password('sally'), email='sally@example.com', first_name='Sally', last_name='Mitchell', is_superuser=False)
    users.objects.create(username='lucaswright23', password=make_password('lucas'), email='lucas@example.com', first_name='Lucas', last_name='Wright', is_superuser=False)
    users.objects.create(username='nina.adams7', password=make_password('nina'), email='nina@example.com', first_name='Nina', last_name='Adams', is_superuser=False)
    users.objects.create(username='derek.stone', password=make_password('derek'), email='derek@example.com', first_name='Derek', last_name='Stone', is_superuser=True, is_staff=True)
    users.objects.create(username='olivia_reads', password=make_password('olivia'), email='olivia@example.com', first_name='Olivia', last_name='Reed', is_superuser=False)
    users.objects.create(username='ethan_bailey90', password=make_password('ethan'), email='ethan@example.com', first_name='Ethan', last_name='Bailey', is_superuser=False)
                       

def remove_data(apps, schema_editor):
    """
    Removes all users from the database.
    """
    users = apps.get_model('quizly', 'User')
    users.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("quizly", "0002_schema"),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
