# Generated by Django 5.2 on 2025-04-15 00:03

from django.db import migrations
from django.contrib.auth.hashers import make_password


def add_data(apps, schema_editor):
    users = apps.get_model('quizly', 'User')
    users.objects.create(username='admin', password=make_password('admin'), email='admin@example.com', first_name='admin', last_name='admin', is_superuser=True, is_staff=True)
    users.objects.create(username='mike', password=make_password('mike'), email='mike@example.com', first_name='mike', last_name='jones', is_superuser=True, is_staff=True)
    users.objects.create(username='bob', password=make_password('bob'), email='bob@example.com', first_name='bob', last_name='carter', is_superuser=False)
    users.objects.create(username='emma', password=make_password('emma'), email='emma@example.com', first_name='emma', last_name='wilson', is_superuser=False)
    users.objects.create(username='james', password=make_password('james'), email='james@example.com', first_name='james', last_name='harris', is_superuser=False)
    users.objects.create(username='sally', password=make_password('sally'), email='sally@example.com', first_name='sally', last_name='mitchell', is_superuser=False)
                         

def remove_data(apps, schema_editor):
    users = apps.get_model('quizly', 'User')
    users.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("quizly", "0002_schema"),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
