# Generated by Django 5.2 on 2025-04-15 00:03

from django.db import migrations
import json
from pathlib import Path


def add_data(apps, schema_editor):
    
    migration_folder = Path(__file__).parent
    json_file_path = migration_folder / 'quizzes.json'
    
    with open(json_file_path, 'r') as file:
        quiz_data = json.load(file)
    
    category_model = apps.get_model('quizly', 'Category')
    
    for category_name in quiz_data.keys():
        category_model.objects.create(name=category_name)


def remove_data(apps, schema_editor):
    categories = apps.get_model('quizly', 'Category')
    categories.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("quizly", "0003_add_users"),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
