# Generated by Django 5.2 on 2025-04-15 00:03

from django.db import migrations
import json
from pathlib import Path


def add_data(apps, schema_editor):
    """
    Adds categories to the database from a JSON file.
    """
    
    # Get the folder that contains the category JSON file
    current_folder = Path(__file__).parent
    json_file_path = current_folder / 'source_data' / 'categories.json'
    
    # Load the JSON file
    with open(json_file_path, 'r') as file:
        category_data = json.load(file)
    
    # Get the model we need to work with
    category_model = apps.get_model('quizly', 'Category')
    
    # Create category objects from each entry in the JSON file
    for name, description in category_data.items():
        category_model.objects.create(name=name, description=description)


def remove_data(apps, schema_editor):
    """
    Removes all categories from the database.
    """
    categories = apps.get_model('quizly', 'Category')
    categories.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("quizly", "0003_add_users"),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
