# Generated by Django 5.2 on 2025-04-15 00:03

from django.db import migrations
import json
import random
from pathlib import Path


def add_data(apps, schema_editor):
    quiz_model = apps.get_model('quizly', 'Quiz')
    category_model = apps.get_model('quizly', 'Category')
    user_model = apps.get_model('quizly', 'User')
    question_model = apps.get_model('quizly', 'Question')
    
    users = list(user_model.objects.exclude(username='admin'))
    
    migration_folder = Path(__file__).parent
    json_file_path = migration_folder / 'quizzes.json'
    
    with open(json_file_path, 'r') as file:
        quiz_data = json.load(file)
    
    for category_name, quizzes_list in quiz_data.items():
        category = category_model.objects.get(name=category_name)
        
        for quiz_info in quizzes_list:
            quiz = quiz_model.objects.create(
                name=quiz_info.get('name', ''),
                description=quiz_info.get('description', ''),
                created_by=random.choice(users),
                category=category
            )
            
            questions = quiz_info.get('questions', [])
            for question_data in questions:
                question_model.objects.create(
                    quiz=quiz,
                    text=question_data.get('text', ''),
                    hint=question_data.get('hint', ''),
                    option1=question_data.get('option1', ''),
                    option2=question_data.get('option2', ''),
                    option3=question_data.get('option3', ''),
                    option4=question_data.get('option4', ''),
                    solution=question_data.get('solution', 1)
                )


def remove_data(apps, schema_editor):
    question_model = apps.get_model('quizly', 'Question')
    question_model.objects.all().delete()

    quiz_model = apps.get_model('quizly', 'Quiz')
    quiz_model.objects.all().delete()
    

class Migration(migrations.Migration):

    dependencies = [
        ("quizly", "0004_add_categories"),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
