# Generated by Django 5.2 on 2025-04-15 00:03

import random
from django.db import migrations


def add_data(apps, schema_editor):
    quiz_attempt_model = apps.get_model('quizly', 'QuizAttempt')
    quiz_model = apps.get_model('quizly', 'Quiz')
    user_model = apps.get_model('quizly', 'User')

    users = list(user_model.objects.exclude(username='admin'))
    quizzes = list(quiz_model.objects.all())
    
    for quiz in quizzes:
        for user in users:
            if random.randint(0, 1) == 1:
                quiz_attempt_model.objects.create(
                    user=user,
                    quiz=quiz,
                    score=random.randint(quiz.questions.count() // 2, quiz.questions.count()),
                    max_score=quiz.questions.count()
                )

    
def remove_data(apps, schema_editor):
    quiz_attempt_model = apps.get_model('quizly', 'QuizAttempt')
    quiz_attempt_model.objects.all().delete()
    

class Migration(migrations.Migration):

    dependencies = [
        ("quizly", "0005_add_quizzes"),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
