# Generated by Django 5.2 on 2025-04-15 00:03

import random
from django.db import migrations


def add_data(apps, schema_editor):
    quiz_rating_model = apps.get_model('quizly', 'QuizRating')
    quiz_model = apps.get_model('quizly', 'Quiz')
    user_model = apps.get_model('quizly', 'User')

    users = list(user_model.objects.exclude(username='admin'))
    quizzes = list(quiz_model.objects.all())
    
    for quiz in quizzes:
        for user in users:
            if random.randint(0, 1) == 1:

                # Generate random rating between 1 and 5, weighted such that a higher rating is more likely
                rating = random.choices(
                    population=[1, 2, 3, 4, 5],
                    weights=[1, 1, 2, 2, 3],
                    k=1
                )[0]               
                
                quiz_rating_model.objects.create(
                    user=user,
                    quiz=quiz,
                    rating=rating,
                )

    
def remove_data(apps, schema_editor):
    quiz_rating_model = apps.get_model('quizly', 'QuizRating')
    quiz_rating_model.objects.all().delete()
    

class Migration(migrations.Migration):

    dependencies = [
        ("quizly", "0006_add_quiz_attempts"),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
