# Generated by Django 5.2 on 2025-05-09 00:25

import random
from django.db import migrations


def add_data(apps, schema_editor):
    # Get the models
    saved_for_later_model = apps.get_model('quizly', 'SavedForLater')
    quiz_model = apps.get_model('quizly', 'Quiz')
    user_model = apps.get_model('quizly', 'User')
    users = list(user_model.objects.exclude(username='admin'))
    quizzes = list(quiz_model.objects.all())
    
    # Loop through all quizzes and users to create saved for later records    
    for user in users:

        # Only save for later 6 quizzes
        for _ in range(6):

            # Pick a random quiz
            quiz = random.choice(quizzes)    

            # Create the saved for later record
            saved_for_later_model.objects.create(
                user=user,
                quiz=quiz,
            )

    
def remove_data(apps, schema_editor):
    saved_for_later_model = apps.get_model('quizly', 'SavedForLater')
    saved_for_later_model.objects.all().delete()
    

class Migration(migrations.Migration):

    dependencies = [
        ("quizly", "0007_add_quiz_ratings"),
    ]

    operations = [
        migrations.RunPython(add_data, reverse_code=remove_data)
    ]
