# Generated by Django 5.2 on 2025-05-09 05:59

from django.db import migrations, models
from quizly.management.commands.build_faiss_index import Command as BuildIndexCommand
from quizly.management.commands.download_search_model import Command as DownloadModelCommand


def run_commands(apps, schema_editor):
    """
    Run the command to download the 
    """
    # Check if the model is already downloaded, if not then download it
    DownloadModelCommand().handle()

    # Build the FAISS index using the downloaded model
    BuildIndexCommand().handle()


class Migration(migrations.Migration):

    dependencies = [
        ('quizly', '0008_add_saved_for_later'),
    ]

    operations = [        
        migrations.RunPython(run_commands, reverse_code=migrations.RunPython.noop)
    ]
